"""Add security_requirements to endpoint_configuration

Revision ID: 4c98851eddaa
Revises: 88e6f31734c7
Create Date: 2026-01-05 08:31:02.960359

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4c98851eddaa'
down_revision = '88e6f31734c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endpoint_configurations', sa.Column('security_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('endpoint_configurations', 'security_requirements')
    # ### end Alembic commands ###
