"""add_deployment_fields_to_generated_mcp_servers

Revision ID: 88e6f31734c7
Revises: cd44fa29c6e1
Create Date: 2025-12-31 12:47:40.562208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88e6f31734c7'
down_revision = 'cd44fa29c6e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add is_deployed as nullable first
    op.add_column('generated_mcp_servers', sa.Column('is_deployed', sa.Boolean(), nullable=True))
    # Set default value for existing records
    op.execute("UPDATE generated_mcp_servers SET is_deployed = FALSE WHERE is_deployed IS NULL")
    # Now make it non-nullable
    op.alter_column('generated_mcp_servers', 'is_deployed', nullable=False)

    op.add_column('generated_mcp_servers', sa.Column('deployed_at', sa.DateTime(), nullable=True))
    op.add_column('generated_mcp_servers', sa.Column('deployment_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_mcp_servers', 'deployment_url')
    op.drop_column('generated_mcp_servers', 'deployed_at')
    op.drop_column('generated_mcp_servers', 'is_deployed')
    # ### end Alembic commands ###
