"""Initial migration

Revision ID: cd44fa29c6e1
Revises: 
Create Date: 2025-12-31 09:22:03.781941

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cd44fa29c6e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('swagger_specs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('spec_version', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('spec_description', sa.Text(), nullable=True),
    sa.Column('base_url', sa.String(length=512), nullable=True),
    sa.Column('original_spec', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_reference', sa.String(length=1024), nullable=True),
    sa.Column('total_endpoints', sa.Integer(), nullable=False),
    sa.Column('endpoints_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source_type IN ('upload', 'url', 'paste', 'endpoint')", name='swagger_specs_source_type_check'),
    sa.CheckConstraint("spec_version IN ('2.0', '3.0.0', '3.0.1', '3.0.2', '3.0.3', '3.1.0')", name='swagger_specs_spec_version_check'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('endpoint_configurations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('swagger_spec_id', sa.UUID(), nullable=False),
    sa.Column('http_method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('operation_id', sa.String(length=255), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('mcp_tool_name', sa.String(length=255), nullable=True),
    sa.Column('mcp_description', sa.Text(), nullable=True),
    sa.Column('parameter_configurations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("http_method IN ('GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'OPTIONS', 'HEAD')", name='endpoint_configurations_method_check'),
    sa.ForeignKeyConstraint(['swagger_spec_id'], ['swagger_specs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('swagger_spec_id', 'http_method', 'path', name='endpoint_configurations_unique_per_spec')
    )
    op.create_table('generated_mcp_servers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('swagger_spec_id', sa.UUID(), nullable=False),
    sa.Column('server_name', sa.String(length=255), nullable=False),
    sa.Column('server_description', sa.Text(), nullable=True),
    sa.Column('generation_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('python_code', sa.Text(), nullable=False),
    sa.Column('requirements_txt', sa.Text(), nullable=False),
    sa.Column('additional_files', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('selected_endpoints_count', sa.Integer(), nullable=False),
    sa.Column('lines_of_code', sa.Integer(), nullable=True),
    sa.Column('generation_status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("generation_status IN ('pending', 'generating', 'completed', 'failed')", name='generated_mcp_servers_status_check'),
    sa.ForeignKeyConstraint(['swagger_spec_id'], ['swagger_specs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generated_mcp_servers')
    op.drop_table('endpoint_configurations')
    op.drop_table('swagger_specs')
    op.drop_table('projects')
    # ### end Alembic commands ###
